MVC/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using MVC.DAL;
using System.IO;

namespace SandO.Controllers
{
    public class CatalogController : Controller
    {
        private ShopContext db = new ShopContext();

        //
        // GET: /Catalog/

        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Branch);
            ViewBag.BranchID = new SelectList(db.Branches, "BranchID", "Name");

            ViewBag.MaxPrice = db.Products.Select(x => x.Price).Max();
            return View(products.ToList());
        }

        [HttpPost]
        public ActionResult Index(string txt, e_Size? size, int? BranchID, int pricesRange, e_Category? category)
        {

            var products = from p in db.Products select p;

            products = products.Where(x => x.Price <= pricesRange);

            if (!string.IsNullOrEmpty(txt))
            {
                products = products.Where(x => x.Name.Contains(txt));
            }
            if (size != null)
            {
                products = products.Where(x => x.Size == size);
            }
            if (BranchID != null)
            {
                products = products.Where(x => x.BranchID == BranchID);
            }
            if (category != null)
            {
                products = products.Where(x => x.Category == category);
            }


            ViewBag.BranchID = new SelectList(db.Branches, "BranchID", "Name");
            ViewBag.MaxPrice = db.Products.Select(x => x.Price).Max();


            return View(products.ToList());      
        }

        //
        // GET: /Catalog/Details/5

        public ActionResult Details(int id = 0)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // GET: /Catalog/Create

        public ActionResult Create()
        {
            ViewBag.BranchID = new SelectList(db.Branches, "BranchID", "Name");
            return View();
        }

        //
        // POST: /Catalog/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product, HttpPostedFileBase file)
        {
            var physicalPath = "";
             
            if (file != null && file.ContentLength > 0)
            {
                var FileName = string.Format("{0}.{1}", Guid.NewGuid(), "jpg");
                var path = Path.Combine(Server.MapPath("~/content/images"), FileName);
                file.SaveAs(path);

                physicalPath = "/content/images/" + FileName; 

            }

            product.Image = physicalPath;
            var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new { x.Key, x.Value.Errors }).ToArray();
            if (ModelState.IsValid || (errors[0].Key == "Image" && errors[0].Errors.Count == 1 && product.Image != "") )
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BranchID = new SelectList(db.Branches, "BranchID", "Name", product.BranchID);
            return View(product);
        }

        //
        // GET: /Catalog/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.BranchID = new SelectList(db.Branches, "BranchID", "Name", product.BranchID);
            ViewBag.image = product.Image;
            return View(product);
        }

        //
        // POST: /Catalog/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, HttpPostedFileBase file)
        {
            var physicalPath = "";

            if (file != null && file.ContentLength > 0)
            {
                var FileName = string.Format("{0}.{1}", Guid.NewGuid(), "jpg");
                var path = Path.Combine(Server.MapPath("~/content/images"), FileName);
                file.SaveAs(path);

                physicalPath = "/content/images/" + FileName;

            }
            if (physicalPath != "")
            {
                product.Image = physicalPath;
            }

            var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new { x.Key, x.Value.Errors }).ToArray();
            if (ModelState.IsValid || (errors[0].Key == "Image" && errors[0].Errors.Count == 1 && product.Image != null))
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BranchID = new SelectList(db.Branches, "BranchID", "Name", product.BranchID);
            return View(product);
        }

        public JsonResult Delete(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();

            ((List<int>)System.Web.HttpContext.Current.Session["shoppingList"]).Remove(id);
            return Json(((List<int>)System.Web.HttpContext.Current.Session["shoppingList"]).Count);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MVC/Views/Catalog/Create.cshtml
@model MVC.Models.Product

@{
    ViewBag.Title = "Create";
}

@section scripts {
<script type="text/javascript">

    $(document).ready(function () {
        $("#image").change(function () {

            $("#pic").val("stam");
        });
    });
    
    

</script>
    }
<h2>הוספת מוצר חדש</h2>

@using (Html.BeginForm("Create", "Catalog", FormMethod.Post, new { enctype = "multipart/form-data" })){
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="multiset">
        <legend>Product</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Category)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(Model => Model.Category,
                                   new SelectList(Enum.GetValues(typeof(MVC.Models.e_Category))))
            @Html.ValidationMessageFor(model => model.Category)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Size)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(Model => Model.Size,
                                   new SelectList(Enum.GetValues(typeof(MVC.Models.e_Size))))
            @Html.ValidationMessageFor(model => model.Size)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Image)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Image, new { id = "pic", style = "display:none;" })
            <input type="file" id="image" name="file" />
            @Html.ValidationMessageFor(model => model.Image)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BranchID)
        </div>
        <div class="editor-field">
            @Html.DropDownList("BranchID", String.Empty)
            @Html.ValidationMessageFor(model => model.BranchID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsOnSale)
            @Html.EditorFor(model => model.IsOnSale)
            @Html.ValidationMessageFor(model => model.IsOnSale)
        </div>

        <p>
            <input type="submit" value="הוסף" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("חזרה לקטלוג", "Index")
</div>

MVC/Views/Catalog/Details.cshtml
@model MVC.Models.Product

@{
    ViewBag.Title = "Details";
}
@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            var map = null;
            getMap();
            UpdatePushpin();
        });

        function getMap() {

            var MapSize = {
                normalSize: {
                    height: 200,
                    width: 500
                },
                fullScreen: {
                    height: screen.height,
                    width: screen.width
                }
            }

            var mapOptions = {
                credentials: "AtLpSxVL1pD68Ueg3TUHYd4lzBkxqsTKJv9r_H0SNFHSDp-cq25L3DOrPsNL4pHJ",
                mapTypeId: Microsoft.Maps.MapTypeId.road,
                center: new Microsoft.Maps.Location($("#coorX").val(),  $("#coorY").val()),
                zoom: 17,
                labelOverlay: Microsoft.Maps.LabelOverlay.hidden,
                height: MapSize.normalSize.height,
                width: MapSize.normalSize.width
            }
            map = new Microsoft.Maps.Map(document.getElementById("branch-map"), mapOptions);
        }

        function UpdatePushpin() {
                var x = $("#coorX").val();
                var y = $("#coorY").val();

                var point1 = new Microsoft.Maps.Location(x, y);
                var pin1 = new Microsoft.Maps.Pushpin(point1, { width: 50, height: 50, draggable: false });
                map.entities.push(pin1);
        }

        $("#pickup").click(function () {
            if ($("#branch-map").hasClass("closed")) {
                $("#branch-map").show();
                $("#branch-map").removeClass("closed");
                $("#branch-map").addClass("open");
            }
            else {
                $("#branch-map").hide();
                $("#branch-map").removeClass("open");
                $("#branch-map").addClass("closed");
            }
        });

        </script>
}

@{var sessionUser = (MVC.Models.Customer)HttpContext.Current.Session["userLogged"];}

<h2>פרטי מוצר</h2>

<fieldset style="margin-left:150px">
    <legend>Product</legend>

    <div style="float:right">
        <div class="display-label-details" >
            @Html.DisplayNameFor(model => model.Name):
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="display-label-details" >
            @Html.DisplayNameFor(model => model.Description):
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Description)
        </div>

        <div class="display-label-details" >
            @Html.DisplayNameFor(model => model.Category):
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Category)
        </div>

        <div class="display-label-details" >
            @Html.DisplayNameFor(model => model.Price):
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Price)
        </div>

        <div class="display-label-details" >
            @Html.DisplayNameFor(model => model.Size):
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Size)
        </div>

        <div class="display-label-details" >
            @Html.DisplayNameFor(model => model.Branch.Name):
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Branch.Name)
        </div>
        <div id="pickup" >
            איסוף עצמי?
            @Html.Hidden("coorX", Model.Branch.CoorX.ToString())
            @Html.Hidden("coorY", Model.Branch.CoorY.ToString())
        </div>
        <div id="branch-map" class="closed" style="display:none"></div>
    </div>

    <img src="@Model.Image" style="width:400px;height:520px; float:left" />
</fieldset>

<p>
    @if (sessionUser != null && sessionUser.IsAdmin)
    {
        @Html.ActionLink("עריכה", "Edit", new { id = Model.ProductID }) <text>|</text>
    }
    @Html.ActionLink("חזרה לקטלוג", "Index")
</p>

MVC/Views/Catalog/Edit.cshtml
@model MVC.Models.Product

@{
    ViewBag.Title = "Edit";
}
@section scripts {
    <script type="text/javascript">

        $(document).ready(function () {
            $("#image").change(function () {

                $("#pic").val("stam");
            });
        });

    </script>
}

<h2>עריכת מוצר</h2>

@using (Html.BeginForm("Edit", "Catalog", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="multiset">
        <legend>Product</legend>

        @Html.HiddenFor(model => model.ProductID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Category)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(Model => Model.Category,
                                   new SelectList(Enum.GetValues(typeof(MVC.Models.e_Category))))
            @Html.ValidationMessageFor(model => model.Category)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Image)
        </div>
        <div class="editor-field">
            <img src="@ViewBag.image" style="width:100px;height:130px;">
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Image, new { id = "pic", style = "display:none;" })
            <input type="file" id="image" name="file" />
            @Html.ValidationMessageFor(model => model.Image)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.BranchID)
        </div>
        <div class="editor-field">
            @Html.DropDownList("BranchID", String.Empty)
            @Html.ValidationMessageFor(model => model.BranchID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsOnSale)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsOnSale)
            @Html.ValidationMessageFor(model => model.IsOnSale)
        </div>

        <p>
            <input type="submit" value="שמור" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("חזרה לקטלוג", "Index")
</div>

@section Scripts {
    <script src="~/scripts/jquery.validate.js"></script>
}

MVC/Views/Catalog/Index.cshtml
@model IEnumerable<MVC.Models.Product>
@using MVC.Models
@{
    ViewBag.Title = "N&O&O - קטלוג";
}

@section scripts {

    <script type="text/javascript">

        $(".addToBag").click(function () {
            var button = $(this);

            $.ajax({
                url: '/ShoppingBag/AddToBag',
                type: 'Post',
                dataType: 'Json',
                data: { productId: $(this).parent().attr("id") },
                success: (function (result) {

                    $(button).text("נוסף לסל");
                    $(button).removeClass("addToBag");
                    $(button).addClass("inBag");
                    $(button).attr("disabled", "disabled");

                    $("#countOfProducts").text("(" + result + ")");
                }),
                error: (function (xhr, status) {
                    alert(status);
                })
            });
        });

        $('[id^=delete_]').click(function () {

            var product = $(this).parent();
            var id = $(this).attr("id").split("_")[1];

            if (confirm("האם אתה בטוח שברצונך למחוק?") == true) {

                $.ajax({
                    url: '/Catalog/Delete',
                    type: 'Post',
                    dataType: 'Json',
                    data: { id: id },
                    success: (function (result) {
                        $(product).hide(500);
                        $("#countOfProducts").text("(" + result + ")");
                    }),
                    error: (function (xhr, status) {
                        alert(status);
                    })
                });
            }
        });

        $("#pricesRange").change(function () {
            $("#max").text($(this).val());
        });

        $(".searchImg").click(function () {
            if ($(".searchBar").hasClass("closed")) {
                $(".searchBar").show();
                $(".searchBar").removeClass("closed");
                $(".searchBar").addClass("open");
            }
            else {
                $(".searchBar").hide();
                $(".searchBar").removeClass("open");
                $(".searchBar").addClass("closed");
            }

        });

    </script>
}

<div id="fb-root"></div>
<script>
(function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.11';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>


<h2>קטלוג</h2>
@{var sessionUser = (MVC.Models.Customer)HttpContext.Current.Session["userLogged"];}
@if (sessionUser != null && sessionUser.IsAdmin)
{
    <p>
        @Html.ActionLink("הוסף פריט חדש", "Create")
    </p>
}
@using (Html.BeginForm("Index", "Catalog", FormMethod.Post))
{
    <div class="searchImg">
        <label>לחיפוש . . .</label>
    </div>
    <div class="searchBar closed" style="display:none">
        <div style="  height: 76px;">
            <label>מידה: </label>
            <div style="display:flex; margin-top:9px;">
                <input type="radio" name="size" value="XS" style="margin-right:20px;"><span>XS</span>
                <input type="radio" name="size" value="S" style="margin-right:20px;"><span>S</span>
                <input type="radio" name="size" value="M" style="margin-right:20px;"><span>M</span>
                <input type="radio" name="size" value="L" style="margin-right:20px;"><span>L</span>
            </div>
        </div>
        <div style="display: flex">
            <div style="margin-left: 30px;">
                <label>שם פריט:</label>
                <input name="txt" value="" style="width: 150px;" />
            </div>
            <div style=" ">
                <label>סניף:</label>
                @Html.DropDownList("BranchID", null, " ", new { style = "width:200px; margin-left:30px;" })
            </div>
            <div style="  padding-left:20px;">
                <label>קטגוריה:</label>
                @Html.DropDownList("category", new SelectList(Enum.GetValues(typeof(MVC.Models.e_Category))), " ", new { style = "width:200px" })
            </div>
            <div style="  height: 76px;">
                <label>טווח מחירים:</label>
                <span id="min">0</span>
                <input id="pricesRange" name="pricesRange" type="range" min="0" max="@ViewBag.MaxPrice" value="@ViewBag.MaxPrice" style="width: 200px" />
                <span id="max" style="margin-left: 20px;">@ViewBag.MaxPrice</span>
            </div>
        </div>
        <div style="float: left;">
            <input type="submit" value="סנן" style="margin:30px;" />
        </div>
    </div>
}

@{var exist = (List<int>)System.Web.HttpContext.Current.Session["shoppingList"];}

<div id="catalog-main">
    @foreach (var item in Model)
    {
        <section class="product-cell">
            @if (item.IsOnSale)
            {
                <img src="~/content/images/onSale1.png" style="float: left" />
            }
            @if (sessionUser != null && sessionUser.IsAdmin)
            {
                <img src="~/content/images/del.png" id="delete_@item.ProductID" class="deleteProduct" title="מחיקת פריט" />
            }

            @Html.ActionLink(" ", "Details", "Catalog", new { id = @item.ProductID }, new
       {
           style = "background: url('" + item.Image + "') no-repeat center right; display:block; height:360px; width:264px;"
       })

            <div id=@item.ProductID class="product-details" style="text-align:center; font-weight:bold">
                <label>@item.Name</label>
                <label>@item.Size</label>
                <label>@item.Price.ToString() ₪</label>

                @if (exist.Contains(item.ProductID))
                {
                    <button type="button" disabled="disabled" class="inBag">נוסף לסל</button>
                }
                else
                {
                    <button type="button" class="addToBag">הוסף לסל</button>
                }

            </div>
            <div class="fb-share-button" data-href="https://www.google.co.il/search?q=@(item.Name)" data-layout="button" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share</a></div>

        </section>
    }
</div>