MVC/Models/Branch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class Branch
    {
        public int BranchID { get; set; }

        [Display(Name = "שם חנות")]
        [Required(ErrorMessage = "שדה חובה")]
        public string Name { get; set; }

        [Display(Name = "עיר")]
        [Required(ErrorMessage = "שדה חובה")]
        public string City { get; set; }

        [Display(Name = "רחוב")]
        [Required(ErrorMessage = "שדה חובה")]
        public string Street { get; set; }

        [Display(Name = "מספר בית")]
        [Required(ErrorMessage = "שדה חובה")]
        public int HouseNo { get; set; }

        [Display(Name = "נקודת אורך")]
        [Required(ErrorMessage = "שדה חובה")]
        public double CoorX { get; set; }

        [Display(Name = "נקודת רוחב")]
        [Required(ErrorMessage = "שדה חובה")]
        public double CoorY { get; set; }
        
        [Display(Name = "מספר טלפון")]
        public string PhoneNo { get; set; }
        
    }
}

MVC/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using MVC.DAL;
using Newtonsoft.Json;
using System.Collections;

namespace MVC.Controllers
{
    public class BranchController : Controller
    {
        private ShopContext db = new ShopContext();

        private static List<DataPoint> _branchesDataPoints = new List<DataPoint>();
        private static List<DataPoint> _customersDataPoints = new List<DataPoint>();
        private static List<DataPoint> _ordersDataPoints = new List<DataPoint>();

        //
        // GET: /Branch/

        public ActionResult Index()
        {
            ViewBag.City = new SelectList(db.Branches.Select(x => x.City).Distinct());

            ViewBag.BranchID = new SelectList(db.Branches, "BranchID", "Name");
            return View(db.Branches.ToList());
        }

        [HttpPost]
        public ActionResult Index(string txt, int? BranchID, string City)
        {

            var branches = from b in db.Branches select b;

            if (!string.IsNullOrEmpty(txt))
            {
                branches = branches.Where(x => x.Name.Contains(txt));
            }
            if (BranchID != null)
            {
                branches = branches.Where(x => x.BranchID == BranchID);
            }
            if (!string.IsNullOrEmpty(City))
            {
                branches = branches.Where(x => x.City == City);
            }

            ViewBag.BranchID = new SelectList(db.Branches, "BranchID", "Name");
            ViewBag.City = new SelectList(db.Branches.Select(x => x.City).Distinct());

            return View(branches);
            
            
        }

        //
        // GET: /Branch/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Branch/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Branch branch)
        {
            if (ModelState.IsValid)
            {
                db.Branches.Add(branch);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(branch);
        }

        //
        // GET: /Branch/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Branch branch = db.Branches.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            return View(branch);
        }

        //
        // POST: /Branch/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Branch branch)
        {
            if (ModelState.IsValid)
            {
                db.Entry(branch).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(branch);
        }

        public JsonResult Delete(int id)
        {
            Branch branch = db.Branches.Find(id);
            db.Branches.Remove(branch);
            db.SaveChanges();
            return Json(id);
        }

        public ActionResult Chart()
        {
            _branchesDataPoints = getDataBranchesForChart();
            _customersDataPoints = getDataCustomersForChart();
            _ordersDataPoints = getDataOrdersForChart();
            ViewBag.BranchesDataPoints = JsonConvert.SerializeObject(_branchesDataPoints);
            ViewBag.CostumersDataPoints = JsonConvert.SerializeObject(_customersDataPoints);
            ViewBag.OredersDataPoints = JsonConvert.SerializeObject(_ordersDataPoints);
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }


        private List<DataPoint> getDataCustomersForChart()
        {
            var Customersdatapoints = db.Customers.GroupBy(b => b.City).Select(grp => new { grp.Key, Count = grp.Count() }).ToList();
            List<DataPoint> datapointsList = new List<DataPoint>();
            foreach (var dCurr in Customersdatapoints)
            {
                datapointsList.Add(new DataPoint(dCurr.Key ?? "", dCurr.Count ));
            }
            return datapointsList;
        }

        private List<DataPoint> getDataOrdersForChart()
        {
            var orderPerCustomerDatapoints = from c in db.Customers
                                   join o in db.Orders on c.CustomerID equals o.CustomerID
                                   group c by c.CustomerID into g
                                   select new { Key = g.Key.ToString(), Count = g.Count() };
            List<DataPoint> datapointsList = new List<DataPoint>();
            foreach (var dCurr in orderPerCustomerDatapoints)
            {
                datapointsList.Add(new DataPoint(dCurr.Key ?? "", dCurr.Count));
            }
            return datapointsList;
        }

        private List<DataPoint> getDataBranchesForChart()
        {
            var branchDatapoints = db.Branches.GroupBy(b => b.City).Select(grp => new { grp.Key, Count = grp.Count() }).ToList();
            List<DataPoint> datapointsList = new List<DataPoint>();
            foreach (var dCurr in branchDatapoints)
            {
                datapointsList.Add(new DataPoint(dCurr.Key ?? "", dCurr.Count));
            }
            return datapointsList;
        }

        JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };
    }
}

MVC/Views/Branch/Chart.cshtml
@{
    ViewBag.Title = "Chart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .axis path,
    .axis line {
        fill: none;
        stroke: #000;
        shape-rendering: crispEdges;
    }

    .bar {
        fill: cornflowerblue;
    }

        .bar:hover {
            fill: lightcoral;
        }

    .x.axis path {
        display: block;
    }

    .d3-tip {
        line-height: 1;
        font-weight: bold;
        padding: 12px;
        background: rgba(0, 0, 0, 0.8);
        color: #fff;
        border-radius: 2px;
    }

        /* Creates a small triangle extender for the tooltip */
        .d3-tip:after {
            box-sizing: border-box;
            display: inline;
            font-size: 10px;
            width: 100%;
            line-height: 1;
            color: rgba(0, 0, 0, 0.8);
            content: "\25BC";
            position: absolute;
            text-align: center;
        }

        /* Style northward tooltips differently */
        .d3-tip.n:after {
            margin: -1px 0 0 0;
            top: 100%;
            left: 0;
        }
</style>
<div style="display:inline-block">
    <h4 style="display:block">פילוח הסניפים:</h4>
    <div id="ChartBranches" style="display:inline-block"></div>
</div>
<div style="display:inline-block; padding-right:100px">
    <h4 style="display:block">פילוח הלקוחות:</h4>
    <div id="ChartCostumers"></div>
</div>
<!--
<div style="display:inline-block; padding-top:30px">
    <h4 style="display:block">פילוח הזמנות:</h4>
    <div id="ChartOrders"></div>
</div>
    -->
@section Scripts {

    <script src="http://d3js.org/d3.v3.min.js"></script>
    <script src="http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js"></script>


    <script type="text/javascript">


        var margin = { top: 40, right: 20, bottom: 30, left: 40 },
            width = 480 - margin.left - margin.right,
            height = 250 - margin.top - margin.bottom;

        var formatPercent = d3.format(".0");

        var x = d3.scale.ordinal()
            .rangeRoundBands([0, width], .1);

        var y = d3.scale.linear()
            .range([height, 0]);

        var xAxis = d3.svg.axis()
            .scale(x)
            .orient("bottom");

        var yAxis = d3.svg.axis()
            .scale(y)
            .orient("left")
            .tickFormat(formatPercent)
            .tickPadding(20);

        var Branchtip = d3.tip()
            .attr('class', 'd3-tip')
            .offset([-10, 0])
            .html(function (d) {
                return "<strong>כמות הסניפים:</strong> <span style='color:red'>" + d.y + "</span>";
            });



        var databranch =  @Html.Raw(ViewBag.BranchesDataPoints);


        x.domain(databranch.map(function (d) { return d.label; }));
        y.domain([0, d3.max(databranch, function (d) { return d.y; })]);


        var svg = d3.select("#ChartBranches").append("svg")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom)
            .append("g")
            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

        svg.call(Branchtip);

        svg.append("g")
            .attr("class", "x axis")
            .attr("transform", "translate(0," + height + ")")
            .call(xAxis);

        svg.append("g")
            .attr("class", "y axis")
            .call(yAxis)
            .append("text")
            .attr("transform", "rotate(-90)")
            .attr("y", 6)
            .attr("dy", ".71em")
            .style("text-anchor", "end");

        svg.selectAll(".bar")
            .data(databranch)
            .enter().append("rect")
            .attr("class", "bar")
            .attr("x", function (d) { return x(d.label); })
            .attr("width", x.rangeBand())
            .attr("y", function (d) { return y(d.y); })
            .attr("height", function (d) { return height - y(d.y); })
            .on('mouseover', Branchtip.show)
            .on('mouseout', Branchtip.hide);




        var Costumertip = d3.tip()
            .attr('class', 'd3-tip')
            .offset([-10, 0])
            .html(function (d) {
                return "<strong>כמות הלקוחות:</strong> <span style='color:red'>" + d.y + "</span>";
            });



        var dataCostumer =  @Html.Raw(ViewBag.CostumersDataPoints);

            x.domain(dataCostumer.map(function (d) { return d.label; }));
            y.domain([0, d3.max(dataCostumer, function (d) { return d.y; })]);


        var svgCostumertip = d3.select("#ChartCostumers").append("svg")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom)
            .append("g")
            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

        svgCostumertip.call(Costumertip);

        svgCostumertip.append("g")
            .attr("class", "x axis")
            .attr("transform", "translate(0," + height + ")")
            .call(xAxis);

        svgCostumertip.append("g")
            .attr("class", "y axis")
            .call(yAxis)
            .append("text")
            .attr("transform", "rotate(-90)")
            .attr("y", 6)
            .attr("dy", ".71em")
            .style("text-anchor", "end");

        svgCostumertip.selectAll(".bar")
            .data(dataCostumer)
            .enter().append("rect")
            .attr("class", "bar")
            .attr("x", function (d) { return x(d.label); })
            .attr("width", x.rangeBand())
            .attr("y", function (d) { return y(d.y); })
            .attr("height", function (d) { return height - y(d.y); })
            .on('mouseover', Costumertip.show)
            .on('mouseout', Costumertip.hide);


/*

        var Orderstip = d3.tip()
            .attr('class', 'd3-tip')
            .offset([-10, 0])
            .html(function (d) {
                return "<strong>כמות ההזמנות:</strong> <span style='color:red'>" + d.y + "</span>";
            });



            var dataOrders =  Html.Raw((ViewBag.OredersDataPoints));

            x.domain(dataOrders.map(function (d) { return d.label; }));
            y.domain([0, d3.max(dataOrders, function (d) { return d.y; })]);

            var svgOrders = d3.select("#ChartOrders").append("svg")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom)
            .append("g")
            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

            svgOrders.call(Orderstip);

            svgOrders.append("g")
            .attr("class", "x axis")
            .attr("transform", "translate(0," + height + ")")
            .call(xAxis);

            svgOrders.append("g")
            .attr("class", "y axis")
            .call(yAxis)
            .append("text")
            .attr("transform", "rotate(-90)")
            .attr("y", 6)
            .attr("dy", ".71em")
            .style("text-anchor", "end");

            svgOrders.selectAll(".bar")
                .data(dataOrders)
            .enter().append("rect")
            .attr("class", "bar")
            .attr("x", function (d) { return x(d.label); })
            .attr("width", x.rangeBand())
            .attr("y", function (d) { return y(d.y); })
            .attr("height", function (d) { return height - y(d.y); })
            .on('mouseover', Costumertip.show)
            .on('mouseout', Costumertip.hide);
            */



    </script>
}

MVC/Views/Branch/Create.cshtml
@model MVC.Models.Branch

@{
    ViewBag.Title = "N&O&O - הוספת סניף";
}

<h2>הוספה</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="multiset">
        <legend>Branch</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.City)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.City, new { autocomplete = "on" })
            @Html.ValidationMessageFor(model => model.City)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Street)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Street)
            @Html.ValidationMessageFor(model => model.Street)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HouseNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HouseNo)
            @Html.ValidationMessageFor(model => model.HouseNo)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.PhoneNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PhoneNo)
        </div>
        @*<div class="editor-label">
            @Html.LabelFor(model => model.CoorX)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CoorX, new { data_val_number = "השדה חייב להכיל ערך מספרי" })
            @Html.ValidationMessageFor(model => model.CoorX)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.CoorY)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CoorY, new { data_val_number = "השדה חייב להכיל ערך מספרי" })
            @Html.ValidationMessageFor(model => model.CoorY)
        </div>

        צריך עזרה במציאת הקורדינטות?  <a href="http://www.latlong.net/convert-address-to-lat-long.html" target="_blank">לחץ כאן</a>*@

        <p>
            <input type="submit" value="שמור" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("בחזרה לסניפים", "Index")
</div>

@section Scripts {
    <script src="~/scripts/jquery.validate.js"></script>
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyD1z1_09VFiXgPeLg91CKSTp9NvcFzcYmE&sensor=false&amp;libraries=places" type="text/javascript"></script>
    <script type="text/javascript">
            function initialize() {
                var options = {
                    types: ['(cities)'],
                    componentRestrictions: { country: "il" }
                };
                var input = document.getElementById('City');
                var autocomplete = new google.maps.places.Autocomplete(input, options);
            }
            google.maps.event.addDomListener(window, 'load', initialize);
    </script>
}

MVC/Views/Branch/Edit.cshtml
@model MVC.Models.Branch

@{
    ViewBag.Title = "N&O&O - עריכת סניף";
}

<h2>עריכת סניף</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset class="multiset">
        <legend>Branch</legend>

        @Html.HiddenFor(model => model.BranchID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.City)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.City)
            @Html.ValidationMessageFor(model => model.City)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Street)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Street)
            @Html.ValidationMessageFor(model => model.Street)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HouseNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HouseNo)
            @Html.ValidationMessageFor(model => model.HouseNo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PhoneNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PhoneNo)
        </div>

        @*<div class="editor-label">
            @Html.LabelFor(model => model.CoorX)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CoorX, new { data_val_number = "השדה חייב להכיל ערך מספרי" })
            @Html.ValidationMessageFor(model => model.CoorX)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.CoorY)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CoorY, new { data_val_number = "השדה חייב להכיל ערך מספרי" })
            @Html.ValidationMessageFor(model => model.CoorY)
        </div>

        צריך עזרה במציאת הקורדינטות?  <a href="http://www.latlong.net/convert-address-to-lat-long.html" target="_blank">לחץ כאן</a>*@
        <p>
            <input type="submit" value="שמור" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("בחזרה לסניפים", "Index")
</div>

@section Scripts {
    <script src="~/scripts/jquery.validate.js"></script>
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyD1z1_09VFiXgPeLg91CKSTp9NvcFzcYmE&sensor=false&amp;libraries=places" type="text/javascript"></script>
    <script type="text/javascript">
        function initialize() {
            var options = {
                types: ['(cities)'],
                componentRestrictions: { country: "il" }
            };
            var input = document.getElementById('City');
            var autocomplete = new google.maps.places.Autocomplete(input, options);
        }
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>

}

MVC/Views/Branch/Index.cshtml
@model IEnumerable<MVC.Models.Branch>

@{
    ViewBag.Title = "N&O&O - רשימת סניפים";
}

@section scripts {

    <script type="text/javascript">
        $('[id^=delete_]').click(function () {

            var branch = $(this).parent().parent();
            var id = $(this).attr("id").split("_")[1];

            if (confirm("האם אתה בטוח שברצונך למחוק?") == true) {

                $.ajax({
                    url: '/Branch/Delete',
                    type: 'Post',
                    dataType: 'Json',
                    data: { id: id },
                    success: (function (result) {
                        $(branch).hide(500);
                    }),
                    error: (function (xhr, status) {
                        alert(status);
                    })
                });
            }
        });

        $(".searchImg").click(function () {
            if ($(".searchBar").hasClass("closed")) {
                $(".searchBar").show();
                $(".searchBar").removeClass("closed");
                $(".searchBar").addClass("open");
            }
            else {
                $(".searchBar").hide();
                $(".searchBar").removeClass("open");
                $(".searchBar").addClass("closed");
            }

        });

    </script>
}
<h2>רשימת סניפים</h2>


@{var sessionUser = (MVC.Models.Customer)HttpContext.Current.Session["userLogged"];}
@if (sessionUser != null && sessionUser.IsAdmin)
{
    <p>
        @Html.ActionLink("הוסף סניף חדש", "Create")
        @Html.ActionLink("ניהול פיזור סניפים", "Chart")
    </p>
}

@using (Html.BeginForm("Index", "Branch", FormMethod.Post))
{
    <div class="searchImg">
        <label>לחיפוש . . .</label>
    </div>
    <div class="searchBar closed" style="display:none">
        <div style="display: flex">
            <div style="margin-left: 30px;">
                <label>הזן שם סניף :</label>
                <input name="txt" value="" style="width: 150px;" />
            </div>
            <div>
                <label>או</label>
                @Html.DropDownList("BranchID", null, "בחר סניף", new { style = "width:200px; margin-left:30px;" })
            </div>
            <div>
                <label>חיפוש לפי עיר:</label>
                @Html.DropDownList("City", null, "בחר עיר", new { style = "width:200px; margin-left:30px;" })
            </div>
            <input type="submit" value="סנן" style="margin-top: 30px;" />
        </div>
    </div>
}


<div class="fullTable">
    @foreach (var item in Model)
    {
        <div id="branch#@item.BranchID" class="branchDetails">
            <label class="brname">@item.Name</label>
            <label>@item.Street @item.HouseNo , @item.City</label>
            <label>@item.PhoneNo</label>

            @Html.Hidden("coorX", item.CoorX)
            @Html.Hidden("coorY", item.CoorY)
            @if (sessionUser != null && sessionUser.IsAdmin)
            {
                <div style="display:table-cell">
                    @Html.ActionLink("ערוך", "Edit", new { id = item.BranchID }) |
                    <img src="~/content/images/delete.png" id="delete_@item.BranchID" class="deleteBranch" title="מחיקת סניף" />
                </div>
            }
        </div>
    }
</div>

<div id="customersMap" style="height: 600px;width: 600px;margin: auto;"></div>
<script>
    function initMap() {
        var mapOptions = {
            zoom: 7,
            center: new google.maps.LatLng(31.9228112, 34.9718815)
        };
        var map = new google.maps.Map($('#customersMap')[0], mapOptions);

        @foreach (var branch in Model)
        {
            <text>
            $.getJSON('http://maps.googleapis.com/maps/api/geocode/json?address=@branch.Street,@branch.City&sensor=false', null, function (data) {
                var custLocation = data.results[0].geometry.location;
                var custMarker = new google.maps.Marker({
                    position: new google.maps.LatLng(custLocation.lat, custLocation.lng),
                    map: map
                });

                var markerContent = '<div class="markerContent">@branch.Name</div>';

                var infowindow = new google.maps.InfoWindow({
                    content: markerContent
                });

                custMarker.addListener('click', function () {
                    infowindow.open(map, custMarker);
                });
            });
            </text>
        }
    }
    </script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCWBqFys-8rdAyBvJ5yZI2KFZfcbVzJU8Q&callback=initMap"></script>